apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foundry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/philipnordmann/kube-ressources.git
    targetRevision: HEAD
    path: apps/foundry
  destination:
    server: https://kubernetes.default.svc
    namespace: foundry